name: Build and Deploy

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Push DOcker image
        run: |
          docker build -t ${{ secrets.AWS_ECR_REGISTRY_URL }}/flaskapp:$GITHUB_SHA app/
          docker login -u AWS -p ${{ secrets.AWS_ACCESS_KEY_ID }} -e none ${{ secrets. AWS_ECR_REGISTRY_URL }}
          docker push ${{ secrets.AWS_ECR_REGISTRY_URL }}/flaskapp:$GITHUB_SHA

  deploy:
    runs-on: ubuntu latest

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy with Terraform
        run: |
          cd terraform
          terraform init
          terraform apply -var "aws_region=${{ secrets.AWS_REGION }}" -var "ami_id=${{ secrets.AMI_ID }}" --auto-approve
        env:
          TF_CLI_ARGS: "-input=flase -no-color"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
